import { ChallengeCategory } from '@prisma/client';
import { CategoryMetadata } from './index';

export const CATEGORY_METADATA: Record<ChallengeCategory, CategoryMetadata> = {
  STUDY: {
    id: 'STUDY',
    label: 'Study',
    banglaLabel: 'পড়াশোনা',
    iconName: 'BookOpen',
    color: '#6366f1',
    bgColor: 'rgba(99, 102, 241, 0.1)',
    borderColor: 'rgba(99, 102, 241, 0.3)',
  },
  CODING: {
    id: 'CODING',
    label: 'Coding',
    banglaLabel: 'কোডিং',
    iconName: 'Code',
    color: '#10b981',
    bgColor: 'rgba(16, 185, 129, 0.1)',
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  SALAT: {
    id: 'SALAT',
    label: 'Salat',
    banglaLabel: 'নামাজ',
    iconName: 'Compass',
    color: '#f59e0b',
    bgColor: 'rgba(245, 158, 11, 0.1)',
    borderColor: 'rgba(245, 158, 11, 0.3)',
  },
  QURAN: {
    id: 'QURAN',
    label: 'Quran & Reflection',
    banglaLabel: 'কোরআন ও তাদাব্বুর',
    iconName: 'Sparkles',
    color: '#06b6d4',
    bgColor: 'rgba(6, 182, 212, 0.1)',
    borderColor: 'rgba(6, 182, 212, 0.3)',
  },
  HABIT: {
    id: 'HABIT',
    label: 'Habit',
    banglaLabel: 'অভ্যাস',
    iconName: 'CheckCircle2',
    color: '#8b5cf6',
    bgColor: 'rgba(139, 92, 246, 0.1)',
    borderColor: 'rgba(139, 92, 246, 0.3)',
  },
  EXERCISE: {
    id: 'EXERCISE',
    label: 'Exercise / Workout',
    banglaLabel: 'ব্যায়াম ও স্বাস্থ্য',
    iconName: 'Activity',
    color: '#f43f5e',
    bgColor: 'rgba(244, 63, 94, 0.1)',
    borderColor: 'rgba(244, 63, 94, 0.3)',
  },
  READING: {
    id: 'READING',
    label: 'Reading',
    banglaLabel: 'বই পড়া',
    iconName: 'Book',
    color: '#0ea5e9',
    bgColor: 'rgba(14, 165, 233, 0.1)',
    borderColor: 'rgba(14, 165, 233, 0.3)',
  },
  DIET: {
    id: 'DIET',
    label: 'Diet & Nutrition',
    banglaLabel: 'খাবার ও পুষ্টি',
    iconName: 'Apple',
    color: '#84cc16',
    bgColor: 'rgba(132, 204, 22, 0.1)',
    borderColor: 'rgba(132, 204, 22, 0.3)',
  },
  ASSIGNMENT: {
    id: 'ASSIGNMENT',
    label: 'Assignment / Task',
    banglaLabel: 'অ্যাসাইনমেন্ট',
    iconName: 'FileCheck',
    color: '#ea580c',
    bgColor: 'rgba(234, 88, 12, 0.1)',
    borderColor: 'rgba(234, 88, 12, 0.3)',
  },
  REVISION: {
    id: 'REVISION',
    label: 'Revision',
    banglaLabel: 'রিভিশন',
    iconName: 'RotateCcw',
    color: '#d946ef',
    bgColor: 'rgba(217, 70, 239, 0.1)',
    borderColor: 'rgba(217, 70, 239, 0.3)',
  },
  EXAM_PREP: {
    id: 'EXAM_PREP',
    label: 'Exam Prep',
    banglaLabel: 'পরীক্ষার প্রস্তুতি',
    iconName: 'Target',
    color: '#ef4444',
    bgColor: 'rgba(239, 68, 68, 0.1)',
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  CUSTOM: {
    id: 'CUSTOM',
    label: 'Custom Goal',
    banglaLabel: 'কাস্টম লক্ষ্য',
    iconName: 'Layers',
    color: '#64748b',
    bgColor: 'rgba(100, 116, 139, 0.1)',
    borderColor: 'rgba(100, 116, 139, 0.3)',
  },
};
