import React from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { Student, ExamDetails, generateQRPayload } from '@/utils/exam-management';

interface AdmitCardProps {
    student: Student;
    exam: ExamDetails;
}

export const AdmitCard = ({ student, exam }: AdmitCardProps) => {
    const qrData = generateQRPayload(student, exam.id, exam.eiin);

    return (
        <div className="border-2 border-slate-800 p-4 h-full flex flex-col justify-between bg-white text-black relative print:break-inside-avoid">
            {/* Cutoff Guides */}
            <div className="absolute -left-[1px] -top-[1px] w-4 h-4 border-l-2 border-t-2 border-black"></div>
            <div className="absolute -right-[1px] -top-[1px] w-4 h-4 border-r-2 border-t-2 border-black"></div>
            <div className="absolute -left-[1px] -bottom-[1px] w-4 h-4 border-l-2 border-b-2 border-black"></div>
            <div className="absolute -right-[1px] -bottom-[1px] w-4 h-4 border-r-2 border-b-2 border-black"></div>

            {/* Header */}
            <div className="text-center border-b-2 border-slate-800 pb-2 mb-2">
                <h2 className="text-xl font-bold uppercase tracking-wide">{exam.schoolName}</h2>
                <div className="text-xs font-semibold mt-1">
                    EIIN: {exam.eiin || 'XXXXXX'} | ADMIT CARD
                </div>
            </div>

            {/* Exam Info */}
            <div className="flex justify-between items-center mb-4 bg-slate-100 p-2 rounded border border-slate-300">
                <div>
                    <span className="text-xs font-bold text-slate-500 uppercase block">Exam</span>
                    <span className="font-bold text-sm">{exam.name}</span>
                </div>
                <div>
                    <span className="text-xs font-bold text-slate-500 uppercase block text-right">Date</span>
                    <span className="font-bold text-sm block text-right">{new Date(exam.date).toLocaleDateString()}</span>
                </div>
            </div>

            {/* Student Details & QR */}
            <div className="flex gap-4 flex-1">
                <div className="flex-1 space-y-2 text-sm">
                    <div className="flex justify-between border-b border-dashed border-slate-300 pb-1">
                        <span className="font-semibold text-slate-600">Name:</span>
                        <span className="font-bold">{student.name}</span>
                    </div>
                    <div className="flex justify-between border-b border-dashed border-slate-300 pb-1">
                        <span className="font-semibold text-slate-600">ID / Reg:</span>
                        <span className="font-mono">{student.registrationId}</span>
                    </div>
                    <div className="flex justify-between border-b border-dashed border-slate-300 pb-1">
                        <span className="font-semibold text-slate-600">Class:</span>
                        <span>{exam.className}</span>
                    </div>
                    <div className="flex justify-between border-b border-dashed border-slate-300 pb-1">
                        <span className="font-semibold text-slate-600">Roll No:</span>
                        <span className="font-bold text-lg">{student.roll}</span>
                    </div>
                </div>

                <div className="flex flex-col items-center justify-center space-y-1">
                    <div className="border border-slate-900 p-1 bg-white">
                        <QRCodeSVG value={qrData} size={80} />
                    </div>
                    <span className="text-[10px] text-slate-500 font-mono">Scan for Info</span>
                </div>
            </div>

            {/* Footer Signatures */}
            <div className="mt-6 pt-4 flex justify-between items-end">
                <div className="text-center w-24">
                    <div className="border-t border-slate-400 w-full mb-1"></div>
                    <p className="text-[10px] font-semibold text-slate-500">Class Teacher</p>
                </div>
                <div className="text-center w-24">
                    <div className="border-t border-slate-400 w-full mb-1"></div>
                    <p className="text-[10px] font-semibold text-slate-500">Head Teacher</p>
                </div>
            </div>
            <div className="text-[9px] text-center text-slate-400 mt-2">
                Generated by DigitalSchool Examination Module
            </div>
        </div>
    );
};

export default AdmitCard;
