import React from 'react';
import { SeatAssignment, ExamDetails } from '@/utils/exam-management';

interface SeatPlanProps {
    assignments: SeatAssignment[];
    exam: ExamDetails;
    roomNumber: number;
}

export const SeatPlanTemplate = ({ assignments, exam, roomNumber }: SeatPlanProps) => {
    return (
        <div className="w-full h-full p-8 bg-white text-black font-serif relative">
            {/* Header */}
            <div className="text-center mb-6 border-b-2 border-black pb-4">
                <h1 className="text-2xl font-bold uppercase mb-1">{exam.schoolName}</h1>
                <h2 className="text-xl font-semibold mb-2">Exam Seat Plan | পরীক্ষার আসন পরিকল্পনা</h2>

                <div className="flex justify-between items-center text-sm font-bold border-t border-dashed border-black pt-2 mt-2 px-8">
                    <span>Exam: {exam.name}</span>
                    <span>Class: {exam.className}</span>
                    <span>Hall/Room: {roomNumber.toString().padStart(2, '0')}</span>
                    <span>Date: {new Date(exam.date).toLocaleDateString()}</span>
                </div>
            </div>

            {/* Table */}
            <div className="w-full">
                <table className="w-full border-collapse border border-black">
                    <thead>
                        <tr className="bg-slate-100">
                            <th className="border border-black px-2 py-2 w-16 text-center">Seat</th>
                            <th className="border border-black px-2 py-2 w-20 text-center">Roll</th>
                            <th className="border border-black px-4 py-2 text-left">Student Name</th>
                            <th className="border border-black px-2 py-2 w-32 text-center">Reg. No</th>
                        </tr>
                    </thead>
                    <tbody>
                        {assignments.map((item, index) => (
                            <tr key={item.student.id} className={index % 2 === 0 ? 'bg-white' : 'bg-slate-50'}>
                                <td className="border border-black px-2 py-2 text-center font-bold text-lg">{item.seatNumber}</td>
                                <td className="border border-black px-2 py-2 text-center font-bold">{item.student.roll}</td>
                                <td className="border border-black px-4 py-2">{item.student.name}</td>
                                <td className="border border-black px-2 py-2 text-center font-mono">{item.student.registrationId}</td>
                            </tr>
                        ))}
                        {/* Fill empty rows if needed to maintain layout? Not necessary for dynamic, but good for consistent look */}
                    </tbody>
                </table>
            </div>

            {/* Footer */}
            <div className="mt-12 flex justify-between items-end px-8">
                <div className="text-center">
                    <div className="w-48 border-b border-black mb-1"></div>
                    <p className="font-bold">Invigilator Signature</p>
                </div>
                <div className="text-center">
                    <div className="w-48 border-b border-black mb-1"></div>
                    <p className="font-bold">Head Teacher Signature</p>
                </div>
            </div>

            <div className="absolute bottom-8 left-0 w-full text-center text-xs text-slate-500">
                Generated by DigitalSchool Examination Committee
            </div>
        </div>
    );
};

export default SeatPlanTemplate;
